development:
  adapter: postgresql
  encoding: unicode
  database: showoff_development
  pool: 5
  username: root
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: sample_postgres_test
  pool: 5
  username: root
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: showoff_production
  pool: 5
  username: root
  password: